### ISSUE TITLE
java.lang.IllegalArgumentException: Can't convert other of type net.minecraft.nbt.NBTTagLongArray

### ISSUE THREAD

**Issue by mica-alex** [Mica-Technologies/LDFAWE#12]
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: java.lang.reflect.InvocationTargetException
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at com.boydti.fawe.forge.v112.ForgeQueue_All.getPrevious(ForgeQueue_All.java:548)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:247)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at com.boydti.fawe.forge.v112.ForgeChunk_All.call(ForgeChunk_All.java:35)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1434)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [com.boydti.fawe.util.MainUtil:handleError:738]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.IllegalArgumentException: Can't convert other of type net.minecraft.nbt.NBTTagLongArray
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at com.sk89q.worldedit.forge.NBTConverter.fromNative(NBTConverter.java:168)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at com.sk89q.worldedit.forge.NBTConverter.fromNative(NBTConverter.java:219)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at com.sk89q.worldedit.forge.NBTConverter.fromNative(NBTConverter.java:157)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at com.sk89q.worldedit.forge.NBTConverter.fromNative(NBTConverter.java:219)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at com.sk89q.worldedit.forge.NBTConverter.fromNative(NBTConverter.java:157)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at com.sk89q.worldedit.forge.NBTConverter.fromNative(NBTConverter.java:219)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at com.sk89q.worldedit.forge.NBTConverter.fromNative(NBTConverter.java:157)
[21:03:34] [ForkJoinPool-6-worker-1/INFO]: [java.lang.Throwable:printStackTrace:635]: 	... 18 more

**Comment by mica-alex** [comment]
Fixed in [LDWE](https://github.com/Mica-Technologies/LDWE): https://github.com/Mica-Technologies/LDWE/commit/791c8b437a5f9dc11067d3b5ac1676a7a38ae8ea
